### ISSUE TITLE
你的master跑不起来

### ISSUE THREAD

**Issue by yodoe** [hujiulong/blog#12]
var node2 = new Node();
    for (var key in this) {
      // Do not clone comments tha...<omitted>... } could not be cloned.
    var node2 = new Node();
    for (var key in this) {
      // Do not clone comments tha...<omitted>... } could not be cloned.
    at Object.serialize (v8.js:268:7)
    at _default (/usr/local/lib/node_modules/parcel-bundler/node_modules/@babel/core/lib/transformation/util/clone-deep.js:22:34)

**Comment by yodoe** [comment]
换个地方
